"""Initial migration Post

Revision ID: 9eebda81a68b
Revises: 73c66cd88307
Create Date: 2025-01-21 19:35:26.194224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eebda81a68b'
down_revision = '73c66cd88307'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.String(length=125), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('subject')

    # ### end Alembic commands ###
